//! `dory-pb` — the protobuf message set (seam 1), generated by `prost` from `proto/*.proto`.
//! The same `.proto` is consumed by Swift via `swift-protobuf`, so `doryd`/`Dory.app` and the Rust
//! crates speak identical messages over vsock, unix, XPC, or SSH.

pub mod agent {
    include!(concat!(env!("OUT_DIR"), "/dory.agent.v1.rs"));
}

pub mod control {
    include!(concat!(env!("OUT_DIR"), "/dory.control.v1.rs"));
}

#[cfg(test)]
mod tests {
    use super::*;
    use prost::Message;

    #[test]
    fn agent_request_round_trips() {
        use agent::agent_request::Method;
        let req = agent::AgentRequest {
            method: Some(Method::ClockSync(agent::ClockSyncRequest {
                host_epoch_ns: 1_700_000_000_000_000_000,
            })),
        };
        let bytes = req.encode_to_vec();
        let back = agent::AgentRequest::decode(bytes.as_slice()).unwrap();
        assert_eq!(req, back);
        match back.method {
            Some(Method::ClockSync(r)) => assert_eq!(r.host_epoch_ns, 1_700_000_000_000_000_000),
            other => panic!("wrong method: {other:?}"),
        }
    }

    #[test]
    fn agent_response_error_round_trips() {
        use agent::agent_response::Result as R;
        let resp = agent::AgentResponse {
            result: Some(R::Error(agent::RpcError {
                code: 42,
                message: "nope".into(),
            })),
        };
        let bytes = resp.encode_to_vec();
        assert_eq!(
            agent::AgentResponse::decode(bytes.as_slice()).unwrap(),
            resp
        );
    }

    #[test]
    fn control_request_round_trips() {
        use control::control_request::Op;
        let req = control::ControlRequest {
            op: Some(Op::ContainerAction(control::ContainerAction {
                id: "abc123".into(),
                action: "restart".into(),
            })),
        };
        let bytes = req.encode_to_vec();
        assert_eq!(
            control::ControlRequest::decode(bytes.as_slice()).unwrap(),
            req
        );
    }

    #[test]
    fn engine_status_enum_defaults_to_stopped() {
        let s = control::EngineStatus::default();
        assert_eq!(s.state(), control::engine_status::State::Stopped);
    }
}
