import Foundation

/// The control surface Dory.app calls over XPC. Keep arguments plist-safe so
/// app, CLI, and tests can all drive doryd without sharing daemon state.
@objc public protocol DorydControl {
    func protocolVersion(reply: @escaping (UInt32) -> Void)
    func dorySocketPath(reply: @escaping (String) -> Void)
    func engineStatus(reply: @escaping (String, String) -> Void)
    func engineStart(reply: @escaping (Bool, String) -> Void)
    func engineStop(reply: @escaping (Bool, String) -> Void)
    func engineSleep(reply: @escaping (Bool, String) -> Void)
    func engineWake(reply: @escaping (Bool, String) -> Void)
    func dockerAgentInfo(reply: @escaping (NSDictionary, String) -> Void)
    func dockerAgentPorts(reply: @escaping (NSDictionary, String) -> Void)
    func dockerAgentTelemetry(reply: @escaping (NSDictionary, String) -> Void)
    func dockerAgentClockSync(reply: @escaping (NSDictionary, String) -> Void)
    func machineCreate(_ config: NSDictionary, reply: @escaping (Bool, NSDictionary, String) -> Void)
    func machineStart(_ machineID: String, reply: @escaping (Bool, NSDictionary, String) -> Void)
    func machineStop(_ machineID: String, reply: @escaping (Bool, NSDictionary, String) -> Void)
    func machineUpdate(_ machineID: String, config: NSDictionary, reply: @escaping (Bool, NSDictionary, String) -> Void)
    func machineDelete(_ machineID: String, reply: @escaping (Bool, String) -> Void)
    func machineList(reply: @escaping (NSArray, String) -> Void)
    func machineStats(_ machineID: String, reply: @escaping (Bool, NSDictionary, String) -> Void)
    func machineExec(_ machineID: String, request: NSDictionary, reply: @escaping (Bool, NSDictionary, String) -> Void)
    func machineProvision(_ machineID: String, request: NSDictionary, reply: @escaping (Bool, NSDictionary, String) -> Void)
    func machineSnapshot(_ machineID: String, request: NSDictionary, reply: @escaping (Bool, NSDictionary, String) -> Void)
    func machineSnapshots(_ machineID: String, reply: @escaping (NSArray, String) -> Void)
    func machineCloneSnapshot(_ machineID: String, snapshotID: String, newID: String, reply: @escaping (Bool, NSDictionary, String) -> Void)
    func machineRestoreSnapshot(_ machineID: String, snapshotID: String, reply: @escaping (Bool, NSDictionary, String) -> Void)
    func machineDeleteSnapshot(_ machineID: String, snapshotID: String, reply: @escaping (Bool, String) -> Void)
    func machineExportSnapshot(_ machineID: String, snapshotID: String, path: String, reply: @escaping (Bool, String) -> Void)
    func machineImportSnapshot(_ path: String, reply: @escaping (Bool, NSDictionary, String) -> Void)
    func remoteConnect(_ config: NSDictionary, reply: @escaping (Bool, NSDictionary, String) -> Void)
    func remotePush(_ machineID: String, localRoot: String, remoteRoot: String, reply: @escaping (Bool, NSDictionary, String) -> Void)
    func remoteStatus(_ machineID: String, reply: @escaping (NSDictionary, String) -> Void)
    func networkReplaceRoutes(_ routes: NSArray, reply: @escaping (Bool, String) -> Void)
    func networkStatus(reply: @escaping (NSDictionary, String) -> Void)
    func networkAuthorizationPlan(reply: @escaping (NSDictionary, String) -> Void)
    func balloonStatus(reply: @escaping (NSDictionary, String) -> Void)
    func balloonReconcile(reply: @escaping (NSDictionary, String) -> Void)
    func idleStatus(reply: @escaping (NSDictionary, String) -> Void)
    func idleHistory(_ limit: Int, reply: @escaping (NSArray, String) -> Void)
    func idleSetMode(_ mode: String, reply: @escaping (Bool, NSDictionary, String) -> Void)
    func idleSetPolicy(_ key: String, value: String, reply: @escaping (Bool, NSDictionary, String) -> Void)
    func health(reply: @escaping (NSDictionary, String) -> Void)
    func doctorJSON(reply: @escaping (String, String) -> Void)
    func incidents(_ limit: Int, reply: @escaping (NSArray, String) -> Void)
}
